### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by ExDonald** [SinnerTF2/powercord-server-info#1]
i get an error when trying to execute the commend
![image](https://user-images.githubusercontent.com/63741142/145677174-0835b375-53cd-4741-b034-5119a1c3a015.png)

![image](https://user-images.githubusercontent.com/63741142/145677241-307a2777-c6ec-4b5f-98ae-bd17e814b522.png)

**Comment by SinnerK0N** [comment]
I will push a fix right away. (also sorry for taking so long, GitHub didn't notify me)

**Comment by SinnerK0N** [comment]
Aight it should work now, lmk if there are any more issues.
